PAGE_SIZE = 4096
PAGE_ATTRIBUTE_SIZE = 8
PAGE_MAX_RECORDS = PAGE_SIZE // PAGE_ATTRIBUTE_SIZE
PAGE_RANGE_SIZE = 8
PAGE_RANGE_MAX_RECORDS = PAGE_RANGE_SIZE * PAGE_MAX_RECORDS

INDIRECTION_COLUMN = 0
RID_COLUMN = 1
TIMESTAMP_COLUMN = 2
SCHEMA_ENCODING_COLUMN = 3
NUM_META_COLUMNS = 4
KEY_COLUMN = NUM_META_COLUMNS

BUFFERPOOL_FRAME_MAX = 50
MERGE_THRESHOLD = 1024

